### ISSUE TITLE
TODO: implement flowtype support

### ISSUE THREAD

**Issue by garetmckinley** [garetmckinley/inferno-boilerplate#11]
In order to solidify this boilerplate and make it bulletproof, it needs support for type checking. Luckily this is something that can be progressively implemented, but the initial support for it needs setup before any files can begin implementing flowtype support.

### Flowtype Setup

- [ ] Add flow to the project's dev dependencies
- [ ] Configure via `.flowconfig`

### Components

- [ ] Button
- [ ] Header
- [ ] Input
- [ ] List
- [ ] MovieRow
- [ ] Nav
- [ ] Wrapper

### Containers

- [ ] AboutPage
- [ ] HomePage

### Templates

- [ ] component.test.js
- [ ] container.test.js
